spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/repo
  profiles:
    active: native
  application:
    name: tutors-config-service
server:
  port: 8888
security:
  user:
    password: cnt-config-secret
